include("${CMAKE_CURRENT_LIST_DIR}/version.cmake")

file(GLOB_RECURSE SOURCES ${LVGL_ROOT_DIR}/src/*.c ${LVGL_ROOT_DIR}/src/*.cpp)

function(lvgl_exclude_source_dir relative_dir)
  list(FILTER SOURCES EXCLUDE REGEX "${LVGL_ROOT_DIR}/src/${relative_dir}(/|$)")
  set(SOURCES "${SOURCES}" PARENT_SCOPE)
endfunction()

function(lvgl_exclude_source_file relative_file)
  list(FILTER SOURCES EXCLUDE REGEX "${LVGL_ROOT_DIR}/src/${relative_file}$")
  set(SOURCES "${SOURCES}" PARENT_SCOPE)
endfunction()

if(ESP_PLATFORM)
  if(NOT CONFIG_LV_USE_DRAW_DMA2D)
    lvgl_exclude_source_dir("draw/dma2d")
  endif()
  if(NOT CONFIG_LV_USE_PPA)
    lvgl_exclude_source_dir("draw/espressif/ppa")
  endif()
  if(NOT CONFIG_LV_USE_DRAW_EVE)
    lvgl_exclude_source_dir("draw/eve")
    lvgl_exclude_source_dir("drivers/draw/eve")
    lvgl_exclude_source_dir("libs/FT800-FT813")
  endif()
  if(NOT CONFIG_LV_USE_DRAW_NANOVG)
    lvgl_exclude_source_dir("draw/nanovg")
  endif()
  if(NOT CONFIG_LV_USE_NANOVG)
    lvgl_exclude_source_dir("libs/nanovg")
  endif()
  if(NOT CONFIG_LV_USE_DRAW_NEMA_GFX)
    lvgl_exclude_source_dir("draw/nema_gfx")
  endif()
  if(NOT CONFIG_LV_USE_PXP)
    lvgl_exclude_source_dir("draw/nxp/pxp")
  endif()
  if(NOT CONFIG_LV_USE_G2D)
    lvgl_exclude_source_dir("draw/nxp/g2d")
  endif()
  if(NOT CONFIG_LV_USE_NXP_ELCDIF)
    lvgl_exclude_source_dir("drivers/display/nxp_elcdif")
  endif()
  if(NOT CONFIG_LV_USE_DRAW_DAVE2D)
    lvgl_exclude_source_dir("draw/renesas/dave2d")
  endif()
  if(NOT CONFIG_LV_USE_DRAW_OPENGLES)
    lvgl_exclude_source_dir("draw/opengles")
  endif()
  if(NOT CONFIG_LV_USE_OPENGLES)
    lvgl_exclude_source_dir("drivers/opengles")
  endif()
  if(NOT CONFIG_LV_USE_DRAW_SDL)
    lvgl_exclude_source_dir("draw/sdl")
  endif()
  if(NOT CONFIG_LV_USE_DRAW_VG_LITE)
    lvgl_exclude_source_dir("draw/vg_lite")
    lvgl_exclude_source_dir("libs/vg_lite_driver")
  endif()

  if(NOT CONFIG_LV_USE_SDL)
    lvgl_exclude_source_dir("drivers/sdl")
  endif()
  if(NOT CONFIG_LV_USE_X11)
    lvgl_exclude_source_dir("drivers/x11")
  endif()
  if(NOT CONFIG_LV_USE_WAYLAND)
    lvgl_exclude_source_dir("drivers/wayland")
  endif()
  if(NOT CONFIG_LV_USE_LINUX_FBDEV)
    lvgl_exclude_source_dir("drivers/display/fb")
  endif()
  if(NOT CONFIG_LV_USE_LINUX_DRM)
    lvgl_exclude_source_dir("drivers/display/drm")
  endif()
  if(NOT CONFIG_LV_USE_NUTTX)
    lvgl_exclude_source_dir("drivers/nuttx")
  endif()
  if(NOT CONFIG_LV_USE_UEFI)
    lvgl_exclude_source_dir("drivers/uefi")
    lvgl_exclude_source_file("libs/fsdrv/lv_fs_uefi.c")
    lvgl_exclude_source_file("stdlib/uefi/lv_mem_core_uefi.c")
  endif()
  if(NOT CONFIG_LV_USE_QNX)
    lvgl_exclude_source_dir("drivers/qnx")
  endif()
  if(NOT CONFIG_LV_USE_TFT_ESPI)
    lvgl_exclude_source_dir("drivers/display/tft_espi")
  endif()
  if(NOT CONFIG_LV_USE_LOVYAN_GFX)
    lvgl_exclude_source_dir("drivers/display/lovyan_gfx")
  endif()
  if(NOT CONFIG_LV_USE_EVDEV)
    lvgl_exclude_source_dir("drivers/evdev")
  endif()
  if(NOT CONFIG_LV_USE_LIBINPUT)
    lvgl_exclude_source_dir("drivers/libinput")
  endif()
  if(NOT CONFIG_LV_USE_ST7735)
    lvgl_exclude_source_dir("drivers/display/st7735")
  endif()
  if(NOT CONFIG_LV_USE_ST7789)
    lvgl_exclude_source_dir("drivers/display/st7789")
  endif()
  if(NOT CONFIG_LV_USE_ST7796)
    lvgl_exclude_source_dir("drivers/display/st7796")
  endif()
  if(NOT CONFIG_LV_USE_ILI9341)
    lvgl_exclude_source_dir("drivers/display/ili9341")
  endif()
  if(NOT CONFIG_LV_USE_GENERIC_MIPI)
    lvgl_exclude_source_dir("drivers/display/lcd")
  endif()
  if(NOT CONFIG_LV_USE_RENESAS_GLCDC)
    lvgl_exclude_source_dir("drivers/display/renesas_glcdc")
  endif()
  if(NOT CONFIG_LV_USE_ST_LTDC)
    lvgl_exclude_source_dir("drivers/display/st_ltdc")
  endif()
  if(NOT CONFIG_LV_USE_FT81X)
    lvgl_exclude_source_dir("drivers/display/ft81x")
  endif()

  if(NOT CONFIG_LV_USE_TEST)
    lvgl_exclude_source_dir("debugging/test")
  endif()
  if(NOT CONFIG_LV_USE_MONKEY)
    lvgl_exclude_source_dir("debugging/monkey")
  endif()
  if(NOT CONFIG_LV_USE_SYSMON)
    lvgl_exclude_source_dir("debugging/sysmon")
  endif()
  if(NOT CONFIG_LV_USE_VG_LITE_THORVG)
    lvgl_exclude_source_dir("debugging/vg_lite_tvg")
  endif()

  if(NOT CONFIG_LV_USE_BMP)
    lvgl_exclude_source_dir("libs/bmp")
  endif()
  if(NOT CONFIG_LV_USE_FREETYPE)
    lvgl_exclude_source_dir("libs/freetype")
  endif()
  if(NOT CONFIG_LV_USE_FFMPEG)
    lvgl_exclude_source_dir("libs/ffmpeg")
  endif()
  if(NOT CONFIG_LV_USE_FS_FROGFS)
    lvgl_exclude_source_dir("libs/frogfs")
    lvgl_exclude_source_file("libs/fsdrv/lv_fs_frogfs.c")
  endif()
  if(NOT CONFIG_LV_USE_GIF)
    lvgl_exclude_source_dir("libs/gif")
    lvgl_exclude_source_file("widgets/gif/lv_gif.c")
  endif()
  if(NOT CONFIG_LV_USE_GLTF)
    lvgl_exclude_source_dir("libs/gltf")
  endif()
  if(NOT CONFIG_LV_USE_GSTREAMER)
    lvgl_exclude_source_dir("libs/gstreamer")
  endif()
  if(NOT CONFIG_LV_USE_LIBJPEG_TURBO)
    lvgl_exclude_source_dir("libs/libjpeg_turbo")
  endif()
  if(NOT CONFIG_LV_USE_LIBPNG)
    lvgl_exclude_source_dir("libs/libpng")
  endif()
  if(NOT CONFIG_LV_USE_LIBWEBP)
    lvgl_exclude_source_dir("libs/libwebp")
  endif()
  if(NOT CONFIG_LV_USE_LZ4)
    lvgl_exclude_source_dir("libs/lz4")
  endif()
  if(NOT CONFIG_LV_USE_QRCODE)
    lvgl_exclude_source_dir("libs/qrcode")
  endif()
  if(NOT CONFIG_LV_USE_BARCODE)
    lvgl_exclude_source_dir("libs/barcode")
  endif()
  if(NOT CONFIG_LV_USE_RLE)
    lvgl_exclude_source_dir("libs/rle")
  endif()
  if(NOT CONFIG_LV_USE_RLOTTIE)
    lvgl_exclude_source_dir("libs/rlottie")
  endif()
  if(NOT CONFIG_LV_USE_SVG)
    lvgl_exclude_source_dir("libs/svg")
  endif()
  if(NOT CONFIG_LV_USE_THORVG)
    lvgl_exclude_source_dir("libs/thorvg")
  endif()
  if(NOT CONFIG_LV_USE_TINY_TTF)
    lvgl_exclude_source_dir("libs/tiny_ttf")
  endif()

  if(NOT CONFIG_LV_USE_FS_POSIX)
    lvgl_exclude_source_file("libs/fsdrv/lv_fs_posix.c")
  endif()
  if(NOT CONFIG_LV_USE_FS_WIN32)
    lvgl_exclude_source_file("libs/fsdrv/lv_fs_win32.c")
  endif()
  if(NOT CONFIG_LV_USE_FS_FATFS)
    lvgl_exclude_source_file("libs/fsdrv/lv_fs_fatfs.c")
  endif()
  if(NOT CONFIG_LV_USE_FS_MEMFS)
    lvgl_exclude_source_file("libs/fsdrv/lv_fs_memfs.c")
  endif()
  if(NOT CONFIG_LV_USE_FS_LITTLEFS)
    lvgl_exclude_source_file("libs/fsdrv/lv_fs_littlefs.c")
  endif()
  if(NOT CONFIG_LV_USE_FS_ARDUINO_ESP_LITTLEFS)
    lvgl_exclude_source_file("libs/fsdrv/lv_fs_arduino_esp_littlefs.cpp")
  endif()
  if(NOT CONFIG_LV_USE_FS_ARDUINO_SD)
    lvgl_exclude_source_file("libs/fsdrv/lv_fs_arduino_sd.cpp")
  endif()
endif()

idf_build_get_property(LV_MICROPYTHON LV_MICROPYTHON)
idf_build_get_property(target IDF_TARGET)

if(LV_MICROPYTHON)
  idf_component_register(
    SRCS
    ${SOURCES}
    INCLUDE_DIRS
    ${LVGL_ROOT_DIR}
    ${LVGL_ROOT_DIR}/src
    ${LVGL_ROOT_DIR}/../
    REQUIRES
    main)
else()
  if(CONFIG_LV_BUILD_EXAMPLES)
    file(GLOB_RECURSE EXAMPLE_SOURCES ${LVGL_ROOT_DIR}/examples/*.c)
    set_source_files_properties(${EXAMPLE_SOURCES} COMPILE_FLAGS "-Wno-unused-variable -Wno-format")
  endif()

  if(CONFIG_LV_BUILD_DEMOS)
    list(APPEND DEMO_SOURCES ${LVGL_ROOT_DIR}/demos/lv_demos.c)
  endif()

  if(CONFIG_LV_USE_DEMO_WIDGETS)
    file(GLOB_RECURSE DEMO_WIDGETS_SOURCES ${LVGL_ROOT_DIR}/demos/widgets/*.c)
    list(APPEND DEMO_SOURCES ${DEMO_WIDGETS_SOURCES})
  endif()
  if(CONFIG_LV_USE_DEMO_KEYPAD_AND_ENCODER)
    file(GLOB_RECURSE DEMO_KEYPAD_AND_ENCODER_SOURCES ${LVGL_ROOT_DIR}/demos/keypad_encoder/*.c)
    list(APPEND DEMO_SOURCES ${DEMO_KEYPAD_AND_ENCODER_SOURCES})
  endif()
  if(CONFIG_LV_USE_DEMO_BENCHMARK)
    file(GLOB_RECURSE DEMO_BENCHMARK_SOURCES ${LVGL_ROOT_DIR}/demos/benchmark/*.c)
    list(APPEND DEMO_SOURCES ${DEMO_BENCHMARK_SOURCES})
  endif()
  if(CONFIG_LV_USE_DEMO_STRESS)
    file(GLOB_RECURSE DEMO_STRESS_SOURCES ${LVGL_ROOT_DIR}/demos/stress/*.c)
    list(APPEND DEMO_SOURCES ${DEMO_STRESS_SOURCES})
  endif()
  if(CONFIG_LV_USE_DEMO_MULTILANG)
    file(GLOB_RECURSE DEMO_MULTILANG_SOURCES ${LVGL_ROOT_DIR}/demos/multilang/*.c)
    list(APPEND DEMO_SOURCES ${DEMO_MULTILANG_SOURCES})
  endif()
  if(CONFIG_LV_USE_DEMO_FLEX_LAYOUT)
    file(GLOB_RECURSE DEMO_FLEX_LAYOUT_SOURCES ${LVGL_ROOT_DIR}/demos/flex_layout/*.c)
    list(APPEND DEMO_SOURCES ${DEMO_FLEX_LAYOUT_SOURCES})
  endif()
  if(CONFIG_LV_USE_DEMO_MUSIC)
    file(GLOB_RECURSE DEMO_MUSIC_SOURCES ${LVGL_ROOT_DIR}/demos/music/*.c)
    list(APPEND DEMO_SOURCES ${DEMO_MUSIC_SOURCES})
    set_source_files_properties(${DEMO_MUSIC_SOURCES} COMPILE_FLAGS "-Wno-format")
  endif()

  set(IDF_COMPONENTS esp_timer log)

  if(${target} STREQUAL "esp32p4")
    list(APPEND IDF_COMPONENTS esp_driver_ppa esp_mm)
  endif()

  if(CONFIG_LV_USE_FS_FATFS)
    list(APPEND IDF_COMPONENTS fatfs)
  endif()

  idf_component_register(SRCS ${SOURCES} ${EXAMPLE_SOURCES} ${DEMO_SOURCES}
      INCLUDE_DIRS ${LVGL_ROOT_DIR} ${LVGL_ROOT_DIR}/src ${LVGL_ROOT_DIR}/../
                   ${LVGL_ROOT_DIR}/examples ${LVGL_ROOT_DIR}/demos
      PRIV_REQUIRES ${IDF_COMPONENTS})
endif()

target_compile_definitions(${COMPONENT_LIB} PUBLIC "-DLV_CONF_INCLUDE_SIMPLE")
target_include_directories(${COMPONENT_LIB} PUBLIC
    "${LVGL_ROOT_DIR}/../smooth_ui_toolkit/example/utils")

if(CONFIG_LV_ATTRIBUTE_FAST_MEM_USE_IRAM)
  target_compile_definitions(${COMPONENT_LIB}
                             PUBLIC "-DLV_ATTRIBUTE_FAST_MEM=IRAM_ATTR")
endif()

if(CONFIG_FREERTOS_SMP)
    target_include_directories(${COMPONENT_LIB} PRIVATE "${IDF_PATH}/components/freertos/FreeRTOS-Kernel-SMP/include/freertos/")
else()
    target_include_directories(${COMPONENT_LIB} PRIVATE "${IDF_PATH}/components/freertos/FreeRTOS-Kernel/include/freertos/")
endif()
